In [ ]:
import tensorflow as tf
print(tf.__version__)
print(tf.test.is_built_with_cuda())
print(tf.test.is_built_with_gpu_support())

2.15.0
True
True


In [ ]:
device = tf.test.gpu_device_name()
#print(device)
if device == '':
    raise SystemError("GPU not found")
else:
    print(device)

/device:GPU:0
/device:GPU:0


Different Ranked Tensors

In [ ]:
rank_0_tensor = tf.constant(3)
print(rank_0_tensor)

tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
rank_1_tensor = tf.constant([1,2,3])
print(rank_1_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
rank_2_tensor = tf.constant([[1,2,3],[4,5,6]])
print(rank_2_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
rank_3_tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(rank_3_tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
rank_4_tensor = tf.constant([[[[1],[2]]],[[[3],[4]]],[[[5],[6]]]])
print(rank_4_tensor)

tf.Tensor(
[[[[1]
   [2]]]


 [[[3]
   [4]]]


 [[[5]
   [6]]]], shape=(3, 1, 2, 1), dtype=int32)


Arithmetics

In [17]:
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)


In [19]:
#numbers passed in tensor functions are treated as tensors
print(tf.multiply([1,2],[3,4]))
print(tf.matmul([[1,1],[1,1]], [[2,2],[2,2]]))

tf.Tensor([3 8], shape=(2,), dtype=int32)
tf.Tensor(
[[4 4]
 [4 4]], shape=(2, 2), dtype=int32)


In [27]:
#declared and passed tensors
t1 = tf.constant([1,2])
t2 = tf.constant([2,4])
print(t1+t2)
print(t2-t1)
print(t1*t2)
print(t2/t1)
print(tf.math.mod(t2,t1))
print(t1 ** t2)
print(t2>t1)
print(t1<t2)
print(-t1)
print(abs(-t1))

tf.Tensor([3 6], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([2 8], shape=(2,), dtype=int32)
tf.Tensor([2. 2.], shape=(2,), dtype=float64)
tf.Tensor([0 0], shape=(2,), dtype=int32)
tf.Tensor([ 1 16], shape=(2,), dtype=int32)
tf.Tensor([ True  True], shape=(2,), dtype=bool)
tf.Tensor([ True  True], shape=(2,), dtype=bool)
tf.Tensor([-1 -2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)


In [30]:
#boolean operations
t3 = tf.constant(True)
t4 = tf.constant(False)
print(t3 & t4)
print(t3 | t4)
print(~t4)


tf.Tensor(False, shape=(), dtype=bool)
tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor(True, shape=(), dtype=bool)


In [42]:
#indexing
print(rank_1_tensor)
print(rank_1_tensor[-2])
print(rank_1_tensor[-2].numpy())
print(tf.random.shuffle(rank_1_tensor))
print(tf.random.normal(rank_1_tensor))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
2
tf.Tensor([3 2 1], shape=(3,), dtype=int32)
tf.Tensor(
[[[ 0.39188352 -1.698322    0.616171  ]
  [ 0.68072784 -1.2283857  -1.4525007 ]]], shape=(1, 2, 3), dtype=float32)


In [38]:
print(rank_2_tensor)
print(rank_2_tensor[:,1]) #middle column

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)


In [45]:
tensor = tf.random.normal([3, 2], mean=10.0, stddev=2.0)
print(tensor)

tf.Tensor(
[[ 9.678548   8.904821 ]
 [10.908193   9.623271 ]
 [ 9.734722   9.5231695]], shape=(3, 2), dtype=float32)
