Variables

In [1]:
import tensorflow as tf

In [2]:
v1 = tf.Variable([1.0,2.0])
print(v1.numpy())
print(v1.shape)
print(v1.dtype)

[1. 2.]
(2,)
<dtype: 'float32'>


In [3]:
ten_v1 = tf.convert_to_tensor(v1)
print(ten_v1)
print(tf.argmax(ten_v1).numpy())  #returns the index of largest value

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
1


In [4]:
print(tf.reshape(v1,(2,1)))

tf.Tensor(
[[1.]
 [2.]], shape=(2, 1), dtype=float32)


In [5]:
a = tf.Variable([1,2])
# try:
#   a.assign([3,4,5])
# except Exception as e:
#   print(e)

a.assign([3,4])
print(a)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4])>


In [6]:
a.assign_add([1,1])
print(a)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 5])>


In [7]:
a = tf.Variable([1.0 , 2.0])
b = a
#b = tf.Variable(a)

a.assign([5,6])
print(a)
print(b)

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([5., 6.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([5., 6.], dtype=float32)>


In [8]:
a = tf.Variable([[1.0,2.0,3.0],[4.0,5.0,6.0]])
b = tf.Variable([[1.0,2.0,3.0]])

with tf.device('GPU:0'):
  k = a * b
print(k)

tf.Tensor(
[[ 1.  4.  9.]
 [ 4. 10. 18.]], shape=(2, 3), dtype=float32)


In [9]:
def var_add(x,y,a):
  x = x + a
  y = y + a
  return x + y

t1 = tf.constant([1,2])
t2 = tf.constant([3,4])
s = 1

print(var_add(t1,t2,s))

using_graph = tf.function(var_add)
print(using_graph(t1,t2,s))

tf.Tensor([6 8], shape=(2,), dtype=int32)
tf.Tensor([6 8], shape=(2,), dtype=int32)


In [10]:
#defining Sequential model with 3 layers
from tensorflow import keras
from keras import layers
model = keras.Sequential([
    layers.Dense(2,activation='relu',name='layer1'),
    layers.Dense(3,activation='relu',name='layer2'),
    layers.Dense(4,activation='relu',name='layer3')
])

x = tf.ones((2,3))
y = model(x)

print(model.weights)

[<tf.Variable 'layer1/kernel:0' shape=(3, 2) dtype=float32, numpy=
array([[ 0.14658988, -1.0210882 ],
       [-0.8079046 ,  0.84836805],
       [-0.2582292 ,  0.32090402]], dtype=float32)>, <tf.Variable 'layer1/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>, <tf.Variable 'layer2/kernel:0' shape=(2, 3) dtype=float32, numpy=
array([[-0.97660923, -0.27052373, -0.6119522 ],
       [ 0.42791378,  0.4493277 ,  0.778535  ]], dtype=float32)>, <tf.Variable 'layer2/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>, <tf.Variable 'layer3/kernel:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.4483746 , -0.64948523, -0.73227656,  0.19253922],
       [-0.27827287,  0.38266814,  0.5336993 , -0.81318045],
       [ 0.57467544, -0.68967426,  0.3684523 , -0.7234448 ]],
      dtype=float32)>, <tf.Variable 'layer3/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]


In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (2, 2)                    8         
                                                                 
 layer2 (Dense)              (2, 3)                    9         
                                                                 
 layer3 (Dense)              (2, 4)                    16        
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [12]:
#ragged tensor

ragged_list = [
    [0,1,2,3],
    [4,5],
    [6,7,8],
    [9]
]

try :
  tensor = tf.constant(ragged_list)
except Exception as e:
  print("Not rectangular")

ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)
print(ragged_tensor.shape)

Not rectangular
<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>
(4, None)


In [13]:
#sparse tensors
sparse_tensor = tf.sparse.SparseTensor(indices=[[0,0],[1,2]],
                                       values=[1,2],
                                       dense_shape=[3,4])
print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
